server:
  port: 8085
spring:
  application:
    name: api
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: menu
          uri: lb://menu
          predicates:
            - Path=/menu/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/services/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**