spring:
  datasource:
    url: jdbc:mysql://token-db:3306/testdb?createDatabaseIfNotExist=true
    username: root
    password: udeshi123
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

res.app.jwtSecret: secretKey
res.app.jwtExpirationMs: 86400000

